### ISSUE TITLE
feature request: support the `critical` level defined in the `wasi-logging` spec

### ISSUE THREAD

**Issue by apepkuss** [rust-lang/log#629] opened 2024-05-15 07:41 UTC
According the [wasi-logging](https://github.com/WebAssembly/wasi-logging/blob/main/wit/logging.wit#L5-L26) spec, the log level defines an additional variant `critical`. However, both [Level](https://github.com/rust-lang/log/blob/master/src/lib.rs#L482) and [LevelFilter](https://github.com/rust-lang/log/blob/master/src/lib.rs#L602) enums of `log` do not support it. Is it possible to provide support for it? Thanks a lot.

**Comment by Thomasdezeeuw** [comment] 2024-05-15 08:19
Duplicate of #334, #626 and many others.

**Closed by Thomasdezeeuw** 2024-05-15 08:19 UTC
